### ISSUE TITLE
submitting order with no selection should generate message

### ISSUE THREAD

**Issue by thomaskise** [thomaskise/itc250-winter2019-p3-food-truck#10]
Right now the page just redisplays, which is maybe ok for beta, but ultimately should have instructions to the user to make a selection before submitting the order.

**Comment by thomaskise** [comment]
I hadn't meant to close this.

**Comment by jenevascherr** [comment]
Hi! We fixed this in class today.

**Comment by thomaskise** [comment]
Put the merge number in a comment and close it!
