### ISSUE TITLE
page errors on index.php

### ISSUE THREAD

**Issue by thomaskise** [thomaskise/itc250-winter2019-p3-food-truck#15]
This one shows on the order page
Notice: Undefined property: Item::$Name in /home/thohar69/kiseharrington.com/food/index.php on line 83

This one shows on the order confirmation page
Notice: Undefined variable: percentTaxRate in /home/thohar69/kiseharrington.com/food/index.php on line 248

**Comment by esteban-gs** [comment]
#20 #19
