### ISSUE TITLE
page error on biz_logic.php

### ISSUE THREAD

**Issue by thomaskise** [thomaskise/itc250-winter2019-p3-food-truck#16]
This shows on the order confirmation page
Warning: A non-numeric value encountered in /home/thohar69/kiseharrington.com/food/includes/biz_logic.php on line 26

**Comment by esteban-gs** [comment]
is this with the latest version of master?

**Comment by esteban-gs** [comment]
Found the error. Fixig now

**Comment by thomaskise** [comment]
Almost ... I just did another merge of Jeneva's code thought that breaks
the whole thing ... getting this error now:

*Parse error*: syntax error, unexpected 'text' (T_STRING), expecting ',' or
';' in */home/thohar69/kiseharrington.com/food/index.php
<http://kiseharrington.com/food/index.php>* on line *79*

Also, we need to clean up the index page ... there's been script references
added that should go in the header file, and functions that should go in
the biz_logic file

I'm going to add issues for these things.

Jeneva ... I'm sorry, but somehow I didn't see these things building up
when I was looking at compares  in the pull requests.  I can help with some
of the clean up.  wondering if we should ahve a quick call on this ....

**Comment by esteban-gs** [comment]
We should all take a pause to get it back working before we add more commits.

**Comment by thomaskise** [comment]
Dang it. It must be because I added the jquery inline with the php. If lines 78 - 113 were taken out and put into an external js file, it can be referenced without causing the error.

**Comment by esteban-gs** [comment]
I have to walk my dog now. but I can take a stab at fixing the error at
7pm. It might take me 1 - 1.5 hours

**Comment by thomaskise** [comment]
Agreed .... I've got to run out now also.  My appointment from last night
that bailed on me, is now reinstated.  I'm tied up for a couple of hours.

I think though it's pretty straight forward to get it started again, and
then just move a vew lines of code from the index ... maybe all to the
header ... I don't really understand the concept of a function wwithin
script tags as is on line 49-55 of index.php ...

**Comment by thomaskise** [comment]
Made a pull request that takes out the jQuery and gave it is own file and referred in. That will take out the error.

**Comment by esteban-gs** [comment]
#18
