### ISSUE TITLE
Fix HTML5 errors

### ISSUE THREAD

**Issue by thomaskise** [thomaskise/itc250-winter2019-p3-food-truck#23]
see errors here:
https://validator.w3.org/nu/?doc=https%3A%2F%2Fkiseharrington.com%2Ffood%2Findex.php

**Comment by thomaskise** [comment]
these are fairly simple updates to html tags.

**Comment by esteban-gs** [comment]
Fixed afew of them

**Comment by thomaskise** [comment]
You're  responsive!  :)

These fixes are all in master. Can they be moved to a branch?

**Comment by thomaskise** [comment]
Fixed a few also
There are three left. 2 align and 1 font that are obsolete for inline html. They need to be moved to css.

**Comment by thomaskise** [comment]
Issue closed in merge #33 Update index.php
