### ISSUE TITLE
Need background image

### ISSUE THREAD

**Issue by thomaskise** [thomaskise/itc250-winter2019-p3-food-truck#26]
/images/foodtruck.jpg was not added when the css was updated.

**Comment by jenevascherr** [comment]
Here is a css file with code for the background image, a little more on centering the contents and margin spacing. Feel free to take out anything that seems in the way.

[bootstrapoverride.css.zip](https://github.com/thomaskise/itc250-winter2019-p3-food-truck/files/2863754/bootstrapoverride.css.zip)

**Comment by thomaskise** [comment]
Closing this issue per team discussions. It would be nice to have an image, but not worth the effort of tracking down the css inheritance issue for our beta site.
